/**
 * Emit tenant-isolation policies into a committed migration.
 *
 *   npm run db:generate:rls
 *
 * ADR-002 asks for RLS to arrive as reviewable SQL in the migration chain
 * rather than as a side effect of a script someone remembers to run. Until now
 * `db:rls` applied policies at runtime: the build gate meant a table could not
 * ship unprotected, but nothing recorded WHICH policies a given environment
 * actually had, and a fresh database depended on a separate command.
 *
 * Only the statements with no secret in them. Role creation carries a password
 * and stays a runtime step — a migration is committed to a public repository.
 *
 * Every statement is idempotent, so the file can be regenerated and re-applied
 * whenever the schema changes without a bespoke diff.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { buildPolicyStatements } from "./sql/rls.ts";

const OUT = "drizzle/9999_rls_policies.sql";
const JOURNAL = "drizzle/meta/_journal.json";

const body = buildPolicyStatements()
  .map((s) => s.trim())
  .filter(Boolean)
  .map((s) => (s.endsWith(";") ? s : `${s};`))
  .join("\n--> statement-breakpoint\n");

const sql = `-- GENERATED by npm run db:generate:rls — do not edit by hand.
-- Tenant isolation policies, derived from the schema. Regenerate after any
-- table with a tenant_id column is added or removed.
${body}
`;

const previous = (() => {
  try { return readFileSync(OUT, "utf8"); } catch { return null; }
})();

if (process.argv.includes("--check")) {
  if (previous !== sql) {
    console.error(
      "\n✗ RLS policies are out of date.\n\n" +
        "  A tenant-scoped table was added or changed without regenerating the\n" +
        "  policy migration. Run `npm run db:generate:rls` and commit the result.\n",
    );
    process.exit(1);
  }
  console.log(`✓ RLS policy migration is in sync (${buildPolicyStatements().length} statements).`);
  process.exit(0);
}

writeFileSync(OUT, sql);

// Register it last in the journal so it applies after every schema migration —
// a policy cannot be created for a table that does not exist yet.
const journal = JSON.parse(readFileSync(JOURNAL, "utf8")) as {
  entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[];
};
const tag = "9999_rls_policies";
const existing = journal.entries.find((e) => e.tag === tag);
const idx = Math.max(...journal.entries.map((e) => e.idx), -1) + 1;
if (existing) {
  // Content changed, so the hash changes; drizzle re-applies it. Idempotent by
  // construction, which is why regenerating in place is safe.
  existing.when = Date.now();
} else {
  journal.entries.push({ idx, version: "7", when: Date.now(), tag, breakpoints: true });
}
writeFileSync(JOURNAL, JSON.stringify(journal, null, 2));

console.log(
  `✓ Wrote ${OUT} — ${buildPolicyStatements().length} statements, ` +
    `sha ${createHash("sha256").update(sql).digest("hex").slice(0, 12)}`,
);
