import { describe, expect, it } from "vitest";
import { calculateGratuity, monthlyGratuityAccrual } from "./gratuity.ts";
import { CT_RATE, CT_THRESHOLD, calculateCorporateTax, calculateVatReturn } from "./tax.ts";

/**
 * THE TESTS THESE FUNCTIONS NEVER HAD.
 *
 * `calculateCorporateTax` had zero coverage of any kind — no unit test, no e2e
 * reference, no service call. `calculateGratuity` and `calculateVatReturn` were
 * exercised only through metric snapshots, which assert that a number has not
 * *changed*, not that it is *right*. A formula wrong on day one is confirmed by
 * its own snapshot forever.
 *
 * Every expected value below is hand-calculated from the statute and written
 * out in the comment above it, so a reviewer can check the arithmetic without
 * running anything. That is the whole point: a fixture generated by calling the
 * function it tests proves only that the function is deterministic.
 *
 * Two areas are deliberately NOT asserted — see the `it.todo` entries. Writing
 * a fixture against a rule nobody has confirmed would enshrine a guess with the
 * authority of a passing test, which is worse than an obvious gap.
 */

const round2 = (n: number) => Math.round(n * 100) / 100;

describe("gratuity — Federal Decree-Law 33/2021 Article 51", () => {
  it("gives no entitlement below one year", () => {
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2025-01-01", asOf: "2025-12-15", // 348 days
    });
    expect(r.entitled).toBe(false);
    expect(r.amount).toBe(0);
  });

  it("pays 21 days' basic wage at exactly one year", () => {
    // daily basic = (10,000 x 12) / 365 = 328.767123...
    // 1 year -> 21 days -> 21 x 328.767123... = 6,904.109589...
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2024-12-31", // 365 days
    });
    expect(r.entitled).toBe(true);
    expect(r.totalDays).toBeCloseTo(21, 6);
    expect(round2(r.amount)).toBe(6904.11);
  });

  it("accrues 21 days per year through the first five years", () => {
    // 2022-01-01 -> 2024-12-31 is 1,095 days = exactly 3.00 years.
    // 3 x 21 = 63 days. daily basic = (10,000 x 12) / 365 = 328.767123...
    // 63 x 328.767123... = 20,712.328767... -> 20,712.33
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2022-01-01", asOf: "2024-12-31",
    });
    expect(r.totalDays).toBeCloseTo(63, 6);
    expect(round2(r.amount)).toBe(20_712.33);
    expect(r.beyondFiveYearDays).toBe(0);
  });

  it("switches to 30 days per year beyond five", () => {
    // 7 years -> (5 x 21) + (2 x 30) = 165 days
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2018-01-01", asOf: "2025-01-01",
    });
    expect(r.firstFiveYearDays).toBeCloseTo(105, 0);
    expect(r.beyondFiveYearDays).toBeGreaterThan(59);
    expect(r.totalDays).toBeGreaterThan(164);
  });

  it("caps the total at two years' TOTAL wage", () => {
    // ~30 years: (5 x 21) + (25.02 x 30) = ~855.6 days.
    // With basic == total == 15,000, daily = 493.1507, so gross = ~421,900,
    // which exceeds the ceiling of 15,000 x 24 = 360,000.
    //
    // Note the cap only bites when basic is a large share of the package:
    // at a 10,000 basic / 15,000 total split the same service earns ~281,000
    // and is NOT capped. That asymmetry is the rule working correctly, and it
    // is why this fixture pins the salary split explicitly.
    const r = calculateGratuity({
      basicSalary: 15_000, totalSalary: 15_000,
      joinedOn: "1995-01-01", asOf: "2025-01-01",
    });
    expect(r.cappedAt).toBe(360_000);
    expect(r.amount).toBe(360_000);
  });

  it("computes on BASIC salary only — allowances are excluded", () => {
    // Same total package, different split. Gratuity must follow basic alone.
    const low = calculateGratuity({
      basicSalary: 5_000, totalSalary: 20_000,
      joinedOn: "2022-01-01", asOf: "2024-12-31",
    });
    const high = calculateGratuity({
      basicSalary: 15_000, totalSalary: 20_000,
      joinedOn: "2022-01-01", asOf: "2024-12-31",
    });
    expect(round2(high.amount)).toBe(round2(low.amount * 3));
  });

  it("forfeits entitlement on Article 44 gross misconduct", () => {
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2015-01-01", asOf: "2025-01-01",
      reason: "gross_misconduct",
    });
    expect(r.entitled).toBe(false);
    expect(r.amount).toBe(0);
  });

  it("excludes unpaid leave from service", () => {
    const withLeave = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2024-12-31", unpaidLeaveDays: 30,
    });
    // 365 - 30 = 335 days, below the one-year minimum.
    expect(withLeave.entitled).toBe(false);
  });

  it("posts the accrual as a movement, so re-running does not double-count", () => {
    const input = {
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2024-12-31",
    };
    const first = monthlyGratuityAccrual(input, 0);
    const second = monthlyGratuityAccrual(input, first.closingLiability);
    expect(round2(second.accrual)).toBe(0);
    expect(second.closingLiability).toBe(first.closingLiability);
  });

  // Q-2 — blocked on a confirmed legal position.
  it.todo(
    "resignation vs termination: BLOCKED on Q-2. The 2021 law is understood to " +
      "have removed the 1/3 and 2/3 reductions, but that has not been confirmed " +
      "with MOHRE or an employment lawyer. A fixture written against a stale rule " +
      "would enshrine the error permanently.",
  );

  it.todo(
    "rehire after a gratuity payout restarts the service clock (EC-05) — the " +
      "service layer does not model it yet, so there is nothing to assert.",
  );
});

describe("VAT return — input apportionment", () => {
  it("recovers all input VAT when every supply is taxable", () => {
    const r = calculateVatReturn({
      standardRatedSupplies: 100_000, outputVat: 5_000,
      zeroRatedSupplies: 0, exemptSupplies: 0, reverseChargeSupplies: 0,
      directlyAttributableInput: 2_000, residualInput: 1_000,
      exemptAttributableInput: 0,
    });
    // ratio = 100,000 / 100,000 = 1 -> all 1,000 residual recoverable
    expect(r.boxes["9_recoverable_input"]).toBe(3_000);
    expect(r.netVatDue).toBe(2_000);
  });

  it("recovers NO residual input VAT when every supply is exempt", () => {
    // The residential-rent case: ratio = 0 / 100,000 = 0.
    const r = calculateVatReturn({
      standardRatedSupplies: 0, outputVat: 0,
      zeroRatedSupplies: 0, exemptSupplies: 100_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 1_000,
      exemptAttributableInput: 500,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(0);
    expect(r.irrecoverableInput).toBe(1_500);
  });

  it("apportions residual input VAT on a mixed portfolio", () => {
    // taxable = 60,000 + 0; total = 60,000 + 40,000 = 100,000 -> ratio 0.6
    // recoverable residual = 10,000 x 0.6 = 6,000
    // total recoverable = 2,000 + 6,000 = 8,000
    // irrecoverable = 500 + (10,000 - 6,000) = 4,500
    const r = calculateVatReturn({
      standardRatedSupplies: 60_000, outputVat: 3_000,
      zeroRatedSupplies: 0, exemptSupplies: 40_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 2_000, residualInput: 10_000,
      exemptAttributableInput: 500,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(8_000);
    expect(r.irrecoverableInput).toBe(4_500);
    expect(r.netVatDue).toBe(3_000 - 8_000);
  });

  it("treats zero-rated supplies as TAXABLE for apportionment", () => {
    // The distinction that catches people out: zero-rated charges 0% but input
    // VAT IS recoverable, so it belongs in the numerator alongside standard.
    // taxable = 0 + 50,000; total = 100,000 -> ratio 0.5, not 0.
    const r = calculateVatReturn({
      standardRatedSupplies: 0, outputVat: 0,
      zeroRatedSupplies: 50_000, exemptSupplies: 50_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 1_000,
      exemptAttributableInput: 0,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(500);
  });

  it("keeps recoverable + irrecoverable equal to the residual exactly", () => {
    // A ratio of 1/3 does not terminate. Taking the irrecoverable share as the
    // remainder is what makes the return's own boxes reconcile.
    const r = calculateVatReturn({
      standardRatedSupplies: 100, outputVat: 5,
      zeroRatedSupplies: 0, exemptSupplies: 200, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 100,
      exemptAttributableInput: 0,
    });
    const recoveredResidual = r.boxes["9_recoverable_input"];
    expect(round2(recoveredResidual + r.irrecoverableInput)).toBe(100);
  });

  it.todo(
    "standalone parking VAT treatment and the floorspace apportionment method: " +
      "BLOCKED on Q-1, pending a tax adviser's written opinion. Parking is " +
      "standard-rated while residential rent is exempt, and the two share the " +
      "units/leases model — this is the highest-risk calculation in the pilot.",
  );

  it.todo("annual actual-use wash-up adjustment (FR-C02) — not implemented yet.");
  it.todo("reverse charge on imported services (FR-C03) — not implemented yet.");
});

describe("corporate tax — Federal Decree-Law 47/2022", () => {
  it("charges nothing below the AED 375,000 nil band", () => {
    const r = calculateCorporateTax({
      accountingProfit: 300_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", electSbr: false,
    });
    expect(r.taxableSlice).toBe(0);
    expect(r.taxDue).toBe(0);
  });

  it("charges 9% only on the slice above the nil band", () => {
    // 500,000 - 375,000 = 125,000 x 9% = 11,250
    const r = calculateCorporateTax({
      accountingProfit: 500_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", electSbr: false,
    });
    expect(r.exemptSlice).toBe(CT_THRESHOLD);
    expect(r.taxableSlice).toBe(125_000);
    expect(r.taxDue).toBe(11_250);
  });

  it("applies Small Business Relief below the revenue cap, while it lasts", () => {
    // Revenue 2.5m <= 3m cap, period ends before 31 Dec 2026 -> nil tax.
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 2_500_000,
      periodEnd: "2026-12-31",
    });
    expect(r.sbrEligible).toBe(true);
    expect(r.sbrApplied).toBe(true);
    expect(r.taxDue).toBe(0);
  });

  it("stops applying relief for periods ending after 31 Dec 2026", () => {
    // Same business, one year later: relief has expired, so 9% above the band.
    // 900,000 - 375,000 = 525,000 x 9% = 47,250
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 2_500_000,
      periodEnd: "2027-12-31",
    });
    expect(r.sbrApplied).toBe(false);
    expect(r.taxDue).toBe(47_250);
  });

  it("denies relief above the AED 3m revenue cap even before expiry", () => {
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 3_000_001,
      periodEnd: "2026-12-31",
    });
    expect(r.sbrEligible).toBe(false);
    expect(r.taxDue).toBeGreaterThan(0);
  });

  it("adds back disallowed expenses before applying the band", () => {
    // (350,000 + 50,000) - 375,000 = 25,000 x 9% = 2,250
    const r = calculateCorporateTax({
      accountingProfit: 350_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", disallowedExpenses: 50_000, electSbr: false,
    });
    expect(r.taxableIncome).toBe(400_000);
    expect(r.taxDue).toBe(2_250);
  });

  it("utilises losses brought forward before charging tax", () => {
    const r = calculateCorporateTax({
      accountingProfit: 500_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", lossesBroughtForward: 100_000, electSbr: false,
    });
    expect(r.lossesUtilised).toBeGreaterThan(0);
    expect(r.taxableIncome).toBeLessThan(500_000);
    expect(r.taxDue).toBeLessThan(11_250);
  });

  it("uses the statutory 9% rate", () => {
    expect(CT_RATE).toBe(0.09);
    expect(CT_THRESHOLD).toBe(375_000);
  });
});
