import { describe, expect, it } from "vitest";
import { calculateGratuity, monthlyGratuityAccrual } from "./gratuity.ts";
import { CT_RATE, CT_THRESHOLD, calculateCorporateTax, calculateVatReturn } from "./tax.ts";

/**
 * THE TESTS THESE FUNCTIONS NEVER HAD.
 *
 * `calculateCorporateTax` had zero coverage of any kind — no unit test, no e2e
 * reference, no service call. `calculateGratuity` and `calculateVatReturn` were
 * exercised only through metric snapshots, which assert that a number has not
 * *changed*, not that it is *right*. A formula wrong on day one is confirmed by
 * its own snapshot forever.
 *
 * Every expected value below is hand-calculated from the statute and written
 * out in the comment above it, so a reviewer can check the arithmetic without
 * running anything. That is the whole point: a fixture generated by calling the
 * function it tests proves only that the function is deterministic.
 *
 * The open legal questions are deliberately NOT asserted — see the `it.todo`
 * entries for Q-1, Q-2 and Q-2b. Writing a fixture against a rule nobody has
 * confirmed would enshrine a guess with the authority of a passing test, which
 * is worse than an obvious gap. Q-2b arrived here the hard way: it was already
 * a passing assertion, on the sibling question to Q-2, worth as much money, and
 * unmarked. Demoting a green test is the right move when the green was a guess.
 */

const round2 = (n: number) => Math.round(n * 100) / 100;

describe("gratuity — Federal Decree-Law 33/2021 Article 51", () => {
  it("gives no entitlement below one year", () => {
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2025-01-01", asOf: "2025-12-15", // 348 days
    });
    expect(r.entitled).toBe(false);
    expect(r.amount).toBe(0);
  });

  it("gives no entitlement at 365 days when the year is a leap year", () => {
    // 2024-01-01 + 365 days is 2024-12-31; the anniversary is 2025-01-01,
    // because 2024 has 366 days. Elapsed days are not a year of service.
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2024-12-31",
    });
    expect(r.serviceDays).toBe(365);
    expect(r.entitled).toBe(false);
    expect(r.amount).toBe(0);
  });

  it("pays 21 days' basic wage at exactly one year", () => {
    // Service is measured to the ANNIVERSARY, so one year from 2024-01-01 is
    // 2025-01-01 — 366 days, because 2024 is a leap year. The entitlement is
    // 21 days either way; that is the point. Valuing at 2024-12-31 instead is
    // one day short of the anniversary and earns nothing (fixture below).
    // daily basic = (10,000 x 12) / 365 = 328.767123...
    // 1 year -> 21 days -> 21 x 328.767123... = 6,904.109589... -> 6,904.11
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2025-01-01",
    });
    expect(r.entitled).toBe(true);
    expect(r.serviceDays).toBe(366);
    expect(r.totalDays).toBeCloseTo(21, 6);
    expect(round2(r.amount)).toBe(6904.11);
  });

  it("accrues 21 days per year through the first five years", () => {
    // 2022-01-01 -> 2025-01-01 is exactly three anniversaries (1,096 days,
    // because 2024 is a leap year — which is precisely why the day count is
    // not what decides this).
    // 3 x 21 = 63 days. daily basic = (10,000 x 12) / 365 = 328.767123...
    // 63 x 328.767123... = 20,712.328767... -> 20,712.33
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2022-01-01", asOf: "2025-01-01",
    });
    expect(r.serviceYears).toBe(3);
    expect(r.totalDays).toBeCloseTo(63, 6);
    expect(round2(r.amount)).toBe(20_712.33);
    expect(r.beyondFiveYearDays).toBe(0);
  });

  it("switches to 30 days per year beyond five", () => {
    // 2018-01-01 -> 2025-01-01 is exactly seven anniversaries.
    // (5 x 21) + (2 x 30) = 105 + 60 = 165 days.
    // 165 x 328.767123... = 54,246.575342... -> 54,246.58
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2018-01-01", asOf: "2025-01-01",
    });
    expect(r.serviceYears).toBe(7);
    expect(r.firstFiveYearDays).toBe(105);
    expect(r.beyondFiveYearDays).toBe(60);
    expect(r.totalDays).toBe(165);
    expect(round2(r.amount)).toBe(54_246.58);
  });

  it("caps the total at two years' TOTAL wage", () => {
    // ~30 years: (5 x 21) + (25.02 x 30) = ~855.6 days.
    // With basic == total == 15,000, daily = 493.1507, so gross = ~421,900,
    // which exceeds the ceiling of 15,000 x 24 = 360,000.
    //
    // Note the cap only bites when basic is a large share of the package:
    // at a 10,000 basic / 15,000 total split the same service earns ~281,000
    // and is NOT capped. That asymmetry is the rule working correctly, and it
    // is why this fixture pins the salary split explicitly.
    const r = calculateGratuity({
      basicSalary: 15_000, totalSalary: 15_000,
      joinedOn: "1995-01-01", asOf: "2025-01-01",
    });
    expect(r.cappedAt).toBe(360_000);
    expect(r.amount).toBe(360_000);
  });

  it("computes on BASIC salary only — allowances are excluded", () => {
    // Same total package, different split. Gratuity must follow basic alone.
    // Three anniversaries -> 63 days for both.
    // low:  63 x (5,000 x 12 / 365 = 164.383561...)  = 10,356.164383... -> 10,356.16
    // high: 63 x (15,000 x 12 / 365 = 493.150684...) = 31,068.493150... -> 31,068.49
    const low = calculateGratuity({
      basicSalary: 5_000, totalSalary: 20_000,
      joinedOn: "2022-01-01", asOf: "2025-01-01",
    });
    const high = calculateGratuity({
      basicSalary: 15_000, totalSalary: 20_000,
      joinedOn: "2022-01-01", asOf: "2025-01-01",
    });
    expect(round2(low.amount)).toBe(10_356.16);
    expect(round2(high.amount)).toBe(31_068.49);
    expect(round2(high.amount)).toBe(round2(low.amount * 3));
  });

  /**
   * CALC-11 — the leap-day band boundary.
   *
   * This is the fixture the register's promise rests on. 2019-01-01 to
   * 2024-01-01 is five years to the day, and it contains the 2020 leap day,
   * so it is 1,826 elapsed days rather than 1,825.
   *
   * The old `serviceDays / 365` arithmetic read that as 5.002739... years and
   * paid the extra 0.002739... of a year at the beyond-five 30-day rate:
   *
   *   105 + (0.002739... x 30) = 105.082191... days
   *   105.082191... x 328.767123... = 34,547.57   <- overstated
   *
   * Measured to the anniversary there is no partial year at all:
   *
   *   5 completed years x 21 = 105 days
   *   daily basic = (10,000 x 12) / 365 = 328.767123287671232876...
   *   105 x 328.767123... = 34,520.547945205479452...  -> 34,520.55
   *
   * AED 27.02 on one employee, and it is the difference between a register the
   * owner can check on paper and one they cannot.
   */
  it("reaches the 21-day cap on the fifth anniversary, not 2.47 days early", () => {
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2019-01-01", asOf: "2024-01-01",
    });
    expect(r.serviceDays).toBe(1826); // 5 x 365 + one leap day
    expect(r.serviceYears).toBe(5);
    expect(r.firstFiveYearDays).toBe(105);
    expect(r.beyondFiveYearDays).toBe(0); // nothing at 30/year yet
    expect(r.totalDays).toBe(105);
    expect(round2(r.amount)).toBe(34_520.55);
  });

  it("does not credit a year of service the day before the anniversary", () => {
    // The same employee one day earlier: 1,825 days, still inside year five.
    // 4 completed years + 364/365 of the fifth:
    //   (4 x 21) + (364/365 x 21) = 84 + 20.942465... = 104.942465... days
    //   104.942465... x 328.767123... = 34,501.632576... -> 34,501.63
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2019-01-01", asOf: "2023-12-31",
    });
    expect(r.serviceDays).toBe(1825);
    expect(r.beyondFiveYearDays).toBe(0);
    expect(round2(r.totalDays)).toBe(104.94);
    expect(round2(r.amount)).toBe(34_501.63);
  });

  it("counts a leap-day joiner's anniversary on 28 February in common years", () => {
    // Joined 2020-02-29. 2025 has no 29th, so the fifth anniversary is
    // 2025-02-28 — 1,826 days later, and the 105-day cap is reached exactly.
    const r = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2020-02-29", asOf: "2025-02-28",
    });
    expect(r.serviceYears).toBe(5);
    expect(r.totalDays).toBe(105);
    expect(round2(r.amount)).toBe(34_520.55);
  });

  it("excludes unpaid leave from service", () => {
    // 30 unpaid days move the service clock start to 2024-01-31, so the first
    // anniversary is 2025-01-31 and 2025-01-01 is 30 days short of it. Without
    // the leave the same valuation date WOULD be entitled — see the one-year
    // fixture above — which is what makes this an actual test of the exclusion.
    const withLeave = calculateGratuity({
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2025-01-01", unpaidLeaveDays: 30,
    });
    expect(withLeave.entitled).toBe(false);
    expect(withLeave.serviceDays).toBe(336); // 366 - 30
  });

  it("posts the accrual as a movement, so re-running does not double-count", () => {
    const input = {
      basicSalary: 10_000, totalSalary: 15_000,
      joinedOn: "2024-01-01", asOf: "2025-01-01",
    };
    const first = monthlyGratuityAccrual(input, 0);
    const second = monthlyGratuityAccrual(input, first.closingLiability);
    expect(round2(first.accrual)).toBe(6904.11);
    expect(round2(second.accrual)).toBe(0);
    expect(second.closingLiability).toBe(first.closingLiability);
  });

  // Q-2 — blocked on a confirmed legal position.
  it.todo(
    "resignation vs termination: BLOCKED on Q-2. The 2021 law is understood to " +
      "have removed the 1/3 and 2/3 reductions, but that has not been confirmed " +
      "with MOHRE or an employment lawyer. A fixture written against a stale rule " +
      "would enshrine the error permanently.",
  );

  // Q-2b — blocked on the same adviser, and worth as much money as Q-2.
  //
  // This WAS a passing assertion that `gross_misconduct` yields AED 0. It was
  // demoted, not deleted: the code still forfeits (see the assumption docblock
  // on that branch in `gratuity.ts`), but a green test asserting a rule nobody
  // has confirmed is the TR-2 failure mode this file's header warns about, and
  // it was the only one of the two sibling questions not parked.
  it.todo(
    "gross-misconduct forfeiture: BLOCKED on Q-2b. The code returns AED 0 for " +
      "an Article 44 dismissal, which was the rule under Art. 120/139 of the " +
      "superseded Federal Law 8/1980. Federal Decree-Law 33/2021 Art. 44 permits " +
      "summary dismissal without notice but appears not to extinguish the Art. 51 " +
      "end-of-service benefit — UNVERIFIED. Worth AED 83,835.62 on a ten-year " +
      "employee at an AED 10,000 basic (255 days x 328.767123). Needs MOHRE or " +
      "an employment lawyer before a fixture is written in either direction.",
  );

  it.todo(
    "rehire after a gratuity payout restarts the service clock (EC-05) — the " +
      "service layer does not model it yet, so there is nothing to assert.",
  );
});

describe("VAT return — input apportionment", () => {
  it("recovers all input VAT when every supply is taxable", () => {
    const r = calculateVatReturn({
      standardRatedSupplies: 100_000, outputVat: 5_000,
      zeroRatedSupplies: 0, exemptSupplies: 0, reverseChargeSupplies: 0,
      directlyAttributableInput: 2_000, residualInput: 1_000,
      exemptAttributableInput: 0,
    });
    // ratio = 100,000 / 100,000 = 1 -> all 1,000 residual recoverable
    expect(r.boxes["9_recoverable_input"]).toBe(3_000);
    expect(r.netVatDue).toBe(2_000);
  });

  it("recovers NO residual input VAT when every supply is exempt", () => {
    // The residential-rent case: ratio = 0 / 100,000 = 0.
    const r = calculateVatReturn({
      standardRatedSupplies: 0, outputVat: 0,
      zeroRatedSupplies: 0, exemptSupplies: 100_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 1_000,
      exemptAttributableInput: 500,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(0);
    expect(r.irrecoverableInput).toBe(1_500);
  });

  it("apportions residual input VAT on a mixed portfolio", () => {
    // taxable = 60,000 + 0; total = 60,000 + 40,000 = 100,000 -> ratio 0.6
    // recoverable residual = 10,000 x 0.6 = 6,000
    // total recoverable = 2,000 + 6,000 = 8,000
    // irrecoverable = 500 + (10,000 - 6,000) = 4,500
    const r = calculateVatReturn({
      standardRatedSupplies: 60_000, outputVat: 3_000,
      zeroRatedSupplies: 0, exemptSupplies: 40_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 2_000, residualInput: 10_000,
      exemptAttributableInput: 500,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(8_000);
    expect(r.irrecoverableInput).toBe(4_500);
    expect(r.netVatDue).toBe(3_000 - 8_000);
  });

  it("treats zero-rated supplies as TAXABLE for apportionment", () => {
    // The distinction that catches people out: zero-rated charges 0% but input
    // VAT IS recoverable, so it belongs in the numerator alongside standard.
    // taxable = 0 + 50,000; total = 100,000 -> ratio 0.5, not 0.
    const r = calculateVatReturn({
      standardRatedSupplies: 0, outputVat: 0,
      zeroRatedSupplies: 50_000, exemptSupplies: 50_000, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 1_000,
      exemptAttributableInput: 0,
    });
    expect(r.boxes["9_recoverable_input"]).toBe(500);
  });

  it("keeps recoverable + irrecoverable equal to the residual exactly", () => {
    // A ratio of 1/3 does not terminate. Taking the irrecoverable share as the
    // remainder is what makes the return's own boxes reconcile.
    const r = calculateVatReturn({
      standardRatedSupplies: 100, outputVat: 5,
      zeroRatedSupplies: 0, exemptSupplies: 200, reverseChargeSupplies: 0,
      directlyAttributableInput: 0, residualInput: 100,
      exemptAttributableInput: 0,
    });
    const recoveredResidual = r.boxes["9_recoverable_input"];
    expect(round2(recoveredResidual + r.irrecoverableInput)).toBe(100);
  });

  it.todo(
    "standalone parking VAT treatment and the floorspace apportionment method: " +
      "BLOCKED on Q-1, pending a tax adviser's written opinion. Parking is " +
      "standard-rated while residential rent is exempt, and the two share the " +
      "units/leases model — this is the highest-risk calculation in the pilot.",
  );

  it.todo("annual actual-use wash-up adjustment (FR-C02) — not implemented yet.");
  it.todo("reverse charge on imported services (FR-C03) — not implemented yet.");
});

describe("corporate tax — Federal Decree-Law 47/2022", () => {
  it("charges nothing below the AED 375,000 nil band", () => {
    const r = calculateCorporateTax({
      accountingProfit: 300_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", electSbr: false,
    });
    expect(r.taxableSlice).toBe(0);
    expect(r.taxDue).toBe(0);
  });

  it("charges 9% only on the slice above the nil band", () => {
    // 500,000 - 375,000 = 125,000 x 9% = 11,250
    const r = calculateCorporateTax({
      accountingProfit: 500_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", electSbr: false,
    });
    expect(r.exemptSlice).toBe(CT_THRESHOLD);
    expect(r.taxableSlice).toBe(125_000);
    expect(r.taxDue).toBe(11_250);
  });

  it("applies Small Business Relief below the revenue cap, while it lasts", () => {
    // Revenue 2.5m <= 3m cap, period ends before 31 Dec 2026 -> nil tax.
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 2_500_000,
      periodEnd: "2026-12-31",
    });
    expect(r.sbrEligible).toBe(true);
    expect(r.sbrApplied).toBe(true);
    expect(r.taxDue).toBe(0);
  });

  it("stops applying relief for periods ending after 31 Dec 2026", () => {
    // Same business, one year later: relief has expired, so 9% above the band.
    // 900,000 - 375,000 = 525,000 x 9% = 47,250
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 2_500_000,
      periodEnd: "2027-12-31",
    });
    expect(r.sbrApplied).toBe(false);
    expect(r.taxDue).toBe(47_250);
  });

  it("denies relief above the AED 3m revenue cap even before expiry", () => {
    const r = calculateCorporateTax({
      accountingProfit: 900_000, revenue: 3_000_001,
      periodEnd: "2026-12-31",
    });
    expect(r.sbrEligible).toBe(false);
    expect(r.taxDue).toBeGreaterThan(0);
  });

  it("adds back disallowed expenses before applying the band", () => {
    // (350,000 + 50,000) - 375,000 = 25,000 x 9% = 2,250
    const r = calculateCorporateTax({
      accountingProfit: 350_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", disallowedExpenses: 50_000, electSbr: false,
    });
    expect(r.taxableIncome).toBe(400_000);
    expect(r.taxDue).toBe(2_250);
  });

  it("utilises losses brought forward before charging tax", () => {
    const r = calculateCorporateTax({
      accountingProfit: 500_000, revenue: 5_000_000,
      periodEnd: "2027-12-31", lossesBroughtForward: 100_000, electSbr: false,
    });
    expect(r.lossesUtilised).toBeGreaterThan(0);
    expect(r.taxableIncome).toBeLessThan(500_000);
    expect(r.taxDue).toBeLessThan(11_250);
  });

  it("uses the statutory 9% rate", () => {
    expect(CT_RATE).toBe(0.09);
    expect(CT_THRESHOLD).toBe(375_000);
  });
});
