-- GENERATED by npm run db:generate:rls — do not edit by hand.
-- Tenant isolation policies, derived from the schema. Regenerate after any
-- table with a tenant_id column is added or removed.
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "accounts" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS accounts_tenant_isolation ON "accounts";
--> statement-breakpoint
CREATE POLICY accounts_tenant_isolation ON "accounts"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "accounts_tenant_rls_idx" ON "accounts" (tenant_id);
--> statement-breakpoint
ALTER TABLE "ai_conversations" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ai_conversations" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS ai_conversations_tenant_isolation ON "ai_conversations";
--> statement-breakpoint
CREATE POLICY ai_conversations_tenant_isolation ON "ai_conversations"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_conversations_tenant_rls_idx" ON "ai_conversations" (tenant_id);
--> statement-breakpoint
ALTER TABLE "ai_insights" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ai_insights" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS ai_insights_tenant_isolation ON "ai_insights";
--> statement-breakpoint
CREATE POLICY ai_insights_tenant_isolation ON "ai_insights"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_insights_tenant_rls_idx" ON "ai_insights" (tenant_id);
--> statement-breakpoint
ALTER TABLE "ai_messages" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ai_messages" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS ai_messages_tenant_isolation ON "ai_messages";
--> statement-breakpoint
CREATE POLICY ai_messages_tenant_isolation ON "ai_messages"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_messages_tenant_rls_idx" ON "ai_messages" (tenant_id);
--> statement-breakpoint
ALTER TABLE "api_tokens" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "api_tokens" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS api_tokens_tenant_isolation ON "api_tokens";
--> statement-breakpoint
CREATE POLICY api_tokens_tenant_isolation ON "api_tokens"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_tokens_tenant_rls_idx" ON "api_tokens" (tenant_id);
--> statement-breakpoint
ALTER TABLE "appointment_services" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "appointment_services" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS appointment_services_tenant_isolation ON "appointment_services";
--> statement-breakpoint
CREATE POLICY appointment_services_tenant_isolation ON "appointment_services"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "appointment_services_tenant_rls_idx" ON "appointment_services" (tenant_id);
--> statement-breakpoint
ALTER TABLE "appointments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "appointments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS appointments_tenant_isolation ON "appointments";
--> statement-breakpoint
CREATE POLICY appointments_tenant_isolation ON "appointments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "appointments_tenant_rls_idx" ON "appointments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "attachments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "attachments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS attachments_tenant_isolation ON "attachments";
--> statement-breakpoint
CREATE POLICY attachments_tenant_isolation ON "attachments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attachments_tenant_rls_idx" ON "attachments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "attendance" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "attendance" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS attendance_tenant_isolation ON "attendance";
--> statement-breakpoint
CREATE POLICY attendance_tenant_isolation ON "attendance"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attendance_tenant_rls_idx" ON "attendance" (tenant_id);
--> statement-breakpoint
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "audit_log" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS audit_log_tenant_isolation ON "audit_log";
--> statement-breakpoint
CREATE POLICY audit_log_tenant_isolation ON "audit_log"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
DROP POLICY IF EXISTS audit_log_global_read ON "audit_log";
--> statement-breakpoint
CREATE POLICY audit_log_global_read ON "audit_log"
          FOR SELECT
          USING (tenant_id IS NULL);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_tenant_rls_idx" ON "audit_log" (tenant_id);
--> statement-breakpoint
ALTER TABLE "automation_runs" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "automation_runs" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS automation_runs_tenant_isolation ON "automation_runs";
--> statement-breakpoint
CREATE POLICY automation_runs_tenant_isolation ON "automation_runs"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "automation_runs_tenant_rls_idx" ON "automation_runs" (tenant_id);
--> statement-breakpoint
ALTER TABLE "automations" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "automations" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS automations_tenant_isolation ON "automations";
--> statement-breakpoint
CREATE POLICY automations_tenant_isolation ON "automations"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "automations_tenant_rls_idx" ON "automations" (tenant_id);
--> statement-breakpoint
ALTER TABLE "bank_accounts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "bank_accounts" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS bank_accounts_tenant_isolation ON "bank_accounts";
--> statement-breakpoint
CREATE POLICY bank_accounts_tenant_isolation ON "bank_accounts"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bank_accounts_tenant_rls_idx" ON "bank_accounts" (tenant_id);
--> statement-breakpoint
ALTER TABLE "bank_transactions" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "bank_transactions" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS bank_transactions_tenant_isolation ON "bank_transactions";
--> statement-breakpoint
CREATE POLICY bank_transactions_tenant_isolation ON "bank_transactions"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bank_transactions_tenant_rls_idx" ON "bank_transactions" (tenant_id);
--> statement-breakpoint
ALTER TABLE "budget_lines" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "budget_lines" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS budget_lines_tenant_isolation ON "budget_lines";
--> statement-breakpoint
CREATE POLICY budget_lines_tenant_isolation ON "budget_lines"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "budget_lines_tenant_rls_idx" ON "budget_lines" (tenant_id);
--> statement-breakpoint
ALTER TABLE "business_unit_modules" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "business_unit_modules" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS business_unit_modules_tenant_isolation ON "business_unit_modules";
--> statement-breakpoint
CREATE POLICY business_unit_modules_tenant_isolation ON "business_unit_modules"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "business_unit_modules_tenant_rls_idx" ON "business_unit_modules" (tenant_id);
--> statement-breakpoint
ALTER TABLE "business_units" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "business_units" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS business_units_tenant_isolation ON "business_units";
--> statement-breakpoint
CREATE POLICY business_units_tenant_isolation ON "business_units"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "business_units_tenant_rls_idx" ON "business_units" (tenant_id);
--> statement-breakpoint
ALTER TABLE "campaign_recipients" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "campaign_recipients" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS campaign_recipients_tenant_isolation ON "campaign_recipients";
--> statement-breakpoint
CREATE POLICY campaign_recipients_tenant_isolation ON "campaign_recipients"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaign_recipients_tenant_rls_idx" ON "campaign_recipients" (tenant_id);
--> statement-breakpoint
ALTER TABLE "campaigns" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "campaigns" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS campaigns_tenant_isolation ON "campaigns";
--> statement-breakpoint
CREATE POLICY campaigns_tenant_isolation ON "campaigns"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaigns_tenant_rls_idx" ON "campaigns" (tenant_id);
--> statement-breakpoint
ALTER TABLE "cash_register_sessions" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "cash_register_sessions" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS cash_register_sessions_tenant_isolation ON "cash_register_sessions";
--> statement-breakpoint
CREATE POLICY cash_register_sessions_tenant_isolation ON "cash_register_sessions"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cash_register_sessions_tenant_rls_idx" ON "cash_register_sessions" (tenant_id);
--> statement-breakpoint
ALTER TABLE "cash_registers" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "cash_registers" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS cash_registers_tenant_isolation ON "cash_registers";
--> statement-breakpoint
CREATE POLICY cash_registers_tenant_isolation ON "cash_registers"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cash_registers_tenant_rls_idx" ON "cash_registers" (tenant_id);
--> statement-breakpoint
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "categories" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS categories_tenant_isolation ON "categories";
--> statement-breakpoint
CREATE POLICY categories_tenant_isolation ON "categories"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "categories_tenant_rls_idx" ON "categories" (tenant_id);
--> statement-breakpoint
ALTER TABLE "channel_listings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "channel_listings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS channel_listings_tenant_isolation ON "channel_listings";
--> statement-breakpoint
CREATE POLICY channel_listings_tenant_isolation ON "channel_listings"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channel_listings_tenant_rls_idx" ON "channel_listings" (tenant_id);
--> statement-breakpoint
ALTER TABLE "channels" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "channels" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS channels_tenant_isolation ON "channels";
--> statement-breakpoint
CREATE POLICY channels_tenant_isolation ON "channels"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channels_tenant_rls_idx" ON "channels" (tenant_id);
--> statement-breakpoint
ALTER TABLE "cheques" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "cheques" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS cheques_tenant_isolation ON "cheques";
--> statement-breakpoint
CREATE POLICY cheques_tenant_isolation ON "cheques"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cheques_tenant_rls_idx" ON "cheques" (tenant_id);
--> statement-breakpoint
ALTER TABLE "commission_entries" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "commission_entries" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS commission_entries_tenant_isolation ON "commission_entries";
--> statement-breakpoint
CREATE POLICY commission_entries_tenant_isolation ON "commission_entries"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "commission_entries_tenant_rls_idx" ON "commission_entries" (tenant_id);
--> statement-breakpoint
ALTER TABLE "commission_rules" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "commission_rules" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS commission_rules_tenant_isolation ON "commission_rules";
--> statement-breakpoint
CREATE POLICY commission_rules_tenant_isolation ON "commission_rules"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "commission_rules_tenant_rls_idx" ON "commission_rules" (tenant_id);
--> statement-breakpoint
ALTER TABLE "communication_consents" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "communication_consents" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS communication_consents_tenant_isolation ON "communication_consents";
--> statement-breakpoint
CREATE POLICY communication_consents_tenant_isolation ON "communication_consents"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "communication_consents_tenant_rls_idx" ON "communication_consents" (tenant_id);
--> statement-breakpoint
ALTER TABLE "document_extractions" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "document_extractions" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS document_extractions_tenant_isolation ON "document_extractions";
--> statement-breakpoint
CREATE POLICY document_extractions_tenant_isolation ON "document_extractions"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_extractions_tenant_rls_idx" ON "document_extractions" (tenant_id);
--> statement-breakpoint
ALTER TABLE "document_lines" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "document_lines" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS document_lines_tenant_isolation ON "document_lines";
--> statement-breakpoint
CREATE POLICY document_lines_tenant_isolation ON "document_lines"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_lines_tenant_rls_idx" ON "document_lines" (tenant_id);
--> statement-breakpoint
ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "documents" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS documents_tenant_isolation ON "documents";
--> statement-breakpoint
CREATE POLICY documents_tenant_isolation ON "documents"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_tenant_rls_idx" ON "documents" (tenant_id);
--> statement-breakpoint
ALTER TABLE "employee_assignments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "employee_assignments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS employee_assignments_tenant_isolation ON "employee_assignments";
--> statement-breakpoint
CREATE POLICY employee_assignments_tenant_isolation ON "employee_assignments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "employee_assignments_tenant_rls_idx" ON "employee_assignments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "employees" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "employees" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS employees_tenant_isolation ON "employees";
--> statement-breakpoint
CREATE POLICY employees_tenant_isolation ON "employees"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "employees_tenant_rls_idx" ON "employees" (tenant_id);
--> statement-breakpoint
ALTER TABLE "exception_dismissals" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "exception_dismissals" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS exception_dismissals_tenant_isolation ON "exception_dismissals";
--> statement-breakpoint
CREATE POLICY exception_dismissals_tenant_isolation ON "exception_dismissals"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "exception_dismissals_tenant_rls_idx" ON "exception_dismissals" (tenant_id);
--> statement-breakpoint
ALTER TABLE "exchange_rates" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "exchange_rates" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS exchange_rates_tenant_isolation ON "exchange_rates";
--> statement-breakpoint
CREATE POLICY exchange_rates_tenant_isolation ON "exchange_rates"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "exchange_rates_tenant_rls_idx" ON "exchange_rates" (tenant_id);
--> statement-breakpoint
ALTER TABLE "fiscal_periods" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "fiscal_periods" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS fiscal_periods_tenant_isolation ON "fiscal_periods";
--> statement-breakpoint
CREATE POLICY fiscal_periods_tenant_isolation ON "fiscal_periods"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fiscal_periods_tenant_rls_idx" ON "fiscal_periods" (tenant_id);
--> statement-breakpoint
ALTER TABLE "fulfilments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "fulfilments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS fulfilments_tenant_isolation ON "fulfilments";
--> statement-breakpoint
CREATE POLICY fulfilments_tenant_isolation ON "fulfilments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fulfilments_tenant_rls_idx" ON "fulfilments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "gratuity_settlements" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "gratuity_settlements" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS gratuity_settlements_tenant_isolation ON "gratuity_settlements";
--> statement-breakpoint
CREATE POLICY gratuity_settlements_tenant_isolation ON "gratuity_settlements"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gratuity_settlements_tenant_rls_idx" ON "gratuity_settlements" (tenant_id);
--> statement-breakpoint
ALTER TABLE "idempotency_keys" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "idempotency_keys" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS idempotency_keys_tenant_isolation ON "idempotency_keys";
--> statement-breakpoint
CREATE POLICY idempotency_keys_tenant_isolation ON "idempotency_keys"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idempotency_keys_tenant_rls_idx" ON "idempotency_keys" (tenant_id);
--> statement-breakpoint
ALTER TABLE "import_batch_rows" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "import_batch_rows" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS import_batch_rows_tenant_isolation ON "import_batch_rows";
--> statement-breakpoint
CREATE POLICY import_batch_rows_tenant_isolation ON "import_batch_rows"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "import_batch_rows_tenant_rls_idx" ON "import_batch_rows" (tenant_id);
--> statement-breakpoint
ALTER TABLE "import_batches" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "import_batches" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS import_batches_tenant_isolation ON "import_batches";
--> statement-breakpoint
CREATE POLICY import_batches_tenant_isolation ON "import_batches"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "import_batches_tenant_rls_idx" ON "import_batches" (tenant_id);
--> statement-breakpoint
ALTER TABLE "installment_plans" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "installment_plans" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS installment_plans_tenant_isolation ON "installment_plans";
--> statement-breakpoint
CREATE POLICY installment_plans_tenant_isolation ON "installment_plans"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "installment_plans_tenant_rls_idx" ON "installment_plans" (tenant_id);
--> statement-breakpoint
ALTER TABLE "installments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "installments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS installments_tenant_isolation ON "installments";
--> statement-breakpoint
CREATE POLICY installments_tenant_isolation ON "installments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "installments_tenant_rls_idx" ON "installments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "interactions" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "interactions" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS interactions_tenant_isolation ON "interactions";
--> statement-breakpoint
CREATE POLICY interactions_tenant_isolation ON "interactions"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "interactions_tenant_rls_idx" ON "interactions" (tenant_id);
--> statement-breakpoint
ALTER TABLE "item_components" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "item_components" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS item_components_tenant_isolation ON "item_components";
--> statement-breakpoint
CREATE POLICY item_components_tenant_isolation ON "item_components"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "item_components_tenant_rls_idx" ON "item_components" (tenant_id);
--> statement-breakpoint
ALTER TABLE "item_variants" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "item_variants" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS item_variants_tenant_isolation ON "item_variants";
--> statement-breakpoint
CREATE POLICY item_variants_tenant_isolation ON "item_variants"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "item_variants_tenant_rls_idx" ON "item_variants" (tenant_id);
--> statement-breakpoint
ALTER TABLE "items" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "items" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS items_tenant_isolation ON "items";
--> statement-breakpoint
CREATE POLICY items_tenant_isolation ON "items"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "items_tenant_rls_idx" ON "items" (tenant_id);
--> statement-breakpoint
ALTER TABLE "job_lines" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "job_lines" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS job_lines_tenant_isolation ON "job_lines";
--> statement-breakpoint
CREATE POLICY job_lines_tenant_isolation ON "job_lines"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "job_lines_tenant_rls_idx" ON "job_lines" (tenant_id);
--> statement-breakpoint
ALTER TABLE "job_photos" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "job_photos" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS job_photos_tenant_isolation ON "job_photos";
--> statement-breakpoint
CREATE POLICY job_photos_tenant_isolation ON "job_photos"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "job_photos_tenant_rls_idx" ON "job_photos" (tenant_id);
--> statement-breakpoint
ALTER TABLE "job_visits" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "job_visits" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS job_visits_tenant_isolation ON "job_visits";
--> statement-breakpoint
CREATE POLICY job_visits_tenant_isolation ON "job_visits"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "job_visits_tenant_rls_idx" ON "job_visits" (tenant_id);
--> statement-breakpoint
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "jobs" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS jobs_tenant_isolation ON "jobs";
--> statement-breakpoint
CREATE POLICY jobs_tenant_isolation ON "jobs"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jobs_tenant_rls_idx" ON "jobs" (tenant_id);
--> statement-breakpoint
ALTER TABLE "journal_lines" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "journal_lines" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS journal_lines_tenant_isolation ON "journal_lines";
--> statement-breakpoint
CREATE POLICY journal_lines_tenant_isolation ON "journal_lines"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journal_lines_tenant_rls_idx" ON "journal_lines" (tenant_id);
--> statement-breakpoint
ALTER TABLE "journals" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "journals" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS journals_tenant_isolation ON "journals";
--> statement-breakpoint
CREATE POLICY journals_tenant_isolation ON "journals"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journals_tenant_rls_idx" ON "journals" (tenant_id);
--> statement-breakpoint
ALTER TABLE "kpi_snapshots" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "kpi_snapshots" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS kpi_snapshots_tenant_isolation ON "kpi_snapshots";
--> statement-breakpoint
CREATE POLICY kpi_snapshots_tenant_isolation ON "kpi_snapshots"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "kpi_snapshots_tenant_rls_idx" ON "kpi_snapshots" (tenant_id);
--> statement-breakpoint
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "leads" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS leads_tenant_isolation ON "leads";
--> statement-breakpoint
CREATE POLICY leads_tenant_isolation ON "leads"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_tenant_rls_idx" ON "leads" (tenant_id);
--> statement-breakpoint
ALTER TABLE "lease_charges" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "lease_charges" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS lease_charges_tenant_isolation ON "lease_charges";
--> statement-breakpoint
CREATE POLICY lease_charges_tenant_isolation ON "lease_charges"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lease_charges_tenant_rls_idx" ON "lease_charges" (tenant_id);
--> statement-breakpoint
ALTER TABLE "leases" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "leases" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS leases_tenant_isolation ON "leases";
--> statement-breakpoint
CREATE POLICY leases_tenant_isolation ON "leases"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leases_tenant_rls_idx" ON "leases" (tenant_id);
--> statement-breakpoint
ALTER TABLE "leave_requests" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "leave_requests" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS leave_requests_tenant_isolation ON "leave_requests";
--> statement-breakpoint
CREATE POLICY leave_requests_tenant_isolation ON "leave_requests"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leave_requests_tenant_rls_idx" ON "leave_requests" (tenant_id);
--> statement-breakpoint
ALTER TABLE "legal_entities" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "legal_entities" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS legal_entities_tenant_isolation ON "legal_entities";
--> statement-breakpoint
CREATE POLICY legal_entities_tenant_isolation ON "legal_entities"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "legal_entities_tenant_rls_idx" ON "legal_entities" (tenant_id);
--> statement-breakpoint
ALTER TABLE "locations" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "locations" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS locations_tenant_isolation ON "locations";
--> statement-breakpoint
CREATE POLICY locations_tenant_isolation ON "locations"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "locations_tenant_rls_idx" ON "locations" (tenant_id);
--> statement-breakpoint
ALTER TABLE "membership_plans" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "membership_plans" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS membership_plans_tenant_isolation ON "membership_plans";
--> statement-breakpoint
CREATE POLICY membership_plans_tenant_isolation ON "membership_plans"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "membership_plans_tenant_rls_idx" ON "membership_plans" (tenant_id);
--> statement-breakpoint
ALTER TABLE "membership_scopes" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "membership_scopes" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS membership_scopes_tenant_isolation ON "membership_scopes";
--> statement-breakpoint
CREATE POLICY membership_scopes_tenant_isolation ON "membership_scopes"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "membership_scopes_tenant_rls_idx" ON "membership_scopes" (tenant_id);
--> statement-breakpoint
ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "memberships" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS memberships_tenant_isolation ON "memberships";
--> statement-breakpoint
CREATE POLICY memberships_tenant_isolation ON "memberships"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "memberships_tenant_rls_idx" ON "memberships" (tenant_id);
--> statement-breakpoint
ALTER TABLE "meter_readings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "meter_readings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS meter_readings_tenant_isolation ON "meter_readings";
--> statement-breakpoint
CREATE POLICY meter_readings_tenant_isolation ON "meter_readings"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meter_readings_tenant_rls_idx" ON "meter_readings" (tenant_id);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS notifications_tenant_isolation ON "notifications";
--> statement-breakpoint
CREATE POLICY notifications_tenant_isolation ON "notifications"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_tenant_rls_idx" ON "notifications" (tenant_id);
--> statement-breakpoint
ALTER TABLE "number_series" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "number_series" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS number_series_tenant_isolation ON "number_series";
--> statement-breakpoint
CREATE POLICY number_series_tenant_isolation ON "number_series"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "number_series_tenant_rls_idx" ON "number_series" (tenant_id);
--> statement-breakpoint
ALTER TABLE "parties" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "parties" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS parties_tenant_isolation ON "parties";
--> statement-breakpoint
CREATE POLICY parties_tenant_isolation ON "parties"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "parties_tenant_rls_idx" ON "parties" (tenant_id);
--> statement-breakpoint
ALTER TABLE "party_business_units" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "party_business_units" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS party_business_units_tenant_isolation ON "party_business_units";
--> statement-breakpoint
CREATE POLICY party_business_units_tenant_isolation ON "party_business_units"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "party_business_units_tenant_rls_idx" ON "party_business_units" (tenant_id);
--> statement-breakpoint
ALTER TABLE "party_contacts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "party_contacts" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS party_contacts_tenant_isolation ON "party_contacts";
--> statement-breakpoint
CREATE POLICY party_contacts_tenant_isolation ON "party_contacts"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "party_contacts_tenant_rls_idx" ON "party_contacts" (tenant_id);
--> statement-breakpoint
ALTER TABLE "party_memberships" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "party_memberships" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS party_memberships_tenant_isolation ON "party_memberships";
--> statement-breakpoint
CREATE POLICY party_memberships_tenant_isolation ON "party_memberships"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "party_memberships_tenant_rls_idx" ON "party_memberships" (tenant_id);
--> statement-breakpoint
ALTER TABLE "payment_allocations" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payment_allocations" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS payment_allocations_tenant_isolation ON "payment_allocations";
--> statement-breakpoint
CREATE POLICY payment_allocations_tenant_isolation ON "payment_allocations"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payment_allocations_tenant_rls_idx" ON "payment_allocations" (tenant_id);
--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS payments_tenant_isolation ON "payments";
--> statement-breakpoint
CREATE POLICY payments_tenant_isolation ON "payments"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_tenant_rls_idx" ON "payments" (tenant_id);
--> statement-breakpoint
ALTER TABLE "payroll_runs" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payroll_runs" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS payroll_runs_tenant_isolation ON "payroll_runs";
--> statement-breakpoint
CREATE POLICY payroll_runs_tenant_isolation ON "payroll_runs"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payroll_runs_tenant_rls_idx" ON "payroll_runs" (tenant_id);
--> statement-breakpoint
ALTER TABLE "payslips" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payslips" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS payslips_tenant_isolation ON "payslips";
--> statement-breakpoint
CREATE POLICY payslips_tenant_isolation ON "payslips"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payslips_tenant_rls_idx" ON "payslips" (tenant_id);
--> statement-breakpoint
ALTER TABLE "posting_rules" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "posting_rules" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS posting_rules_tenant_isolation ON "posting_rules";
--> statement-breakpoint
CREATE POLICY posting_rules_tenant_isolation ON "posting_rules"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "posting_rules_tenant_rls_idx" ON "posting_rules" (tenant_id);
--> statement-breakpoint
ALTER TABLE "price_list_entries" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "price_list_entries" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS price_list_entries_tenant_isolation ON "price_list_entries";
--> statement-breakpoint
CREATE POLICY price_list_entries_tenant_isolation ON "price_list_entries"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "price_list_entries_tenant_rls_idx" ON "price_list_entries" (tenant_id);
--> statement-breakpoint
ALTER TABLE "price_lists" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "price_lists" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS price_lists_tenant_isolation ON "price_lists";
--> statement-breakpoint
CREATE POLICY price_lists_tenant_isolation ON "price_lists"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "price_lists_tenant_rls_idx" ON "price_lists" (tenant_id);
--> statement-breakpoint
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "projects" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS projects_tenant_isolation ON "projects";
--> statement-breakpoint
CREATE POLICY projects_tenant_isolation ON "projects"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "projects_tenant_rls_idx" ON "projects" (tenant_id);
--> statement-breakpoint
ALTER TABLE "resources" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "resources" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS resources_tenant_isolation ON "resources";
--> statement-breakpoint
CREATE POLICY resources_tenant_isolation ON "resources"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resources_tenant_rls_idx" ON "resources" (tenant_id);
--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "roles" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS roles_tenant_isolation ON "roles";
--> statement-breakpoint
CREATE POLICY roles_tenant_isolation ON "roles"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
DROP POLICY IF EXISTS roles_global_read ON "roles";
--> statement-breakpoint
CREATE POLICY roles_global_read ON "roles"
          FOR SELECT
          USING (tenant_id IS NULL);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "roles_tenant_rls_idx" ON "roles" (tenant_id);
--> statement-breakpoint
ALTER TABLE "salary_advances" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "salary_advances" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS salary_advances_tenant_isolation ON "salary_advances";
--> statement-breakpoint
CREATE POLICY salary_advances_tenant_isolation ON "salary_advances"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "salary_advances_tenant_rls_idx" ON "salary_advances" (tenant_id);
--> statement-breakpoint
ALTER TABLE "saved_views" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "saved_views" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS saved_views_tenant_isolation ON "saved_views";
--> statement-breakpoint
CREATE POLICY saved_views_tenant_isolation ON "saved_views"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_views_tenant_rls_idx" ON "saved_views" (tenant_id);
--> statement-breakpoint
ALTER TABLE "serial_units" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "serial_units" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS serial_units_tenant_isolation ON "serial_units";
--> statement-breakpoint
CREATE POLICY serial_units_tenant_isolation ON "serial_units"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "serial_units_tenant_rls_idx" ON "serial_units" (tenant_id);
--> statement-breakpoint
ALTER TABLE "service_contracts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "service_contracts" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS service_contracts_tenant_isolation ON "service_contracts";
--> statement-breakpoint
CREATE POLICY service_contracts_tenant_isolation ON "service_contracts"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "service_contracts_tenant_rls_idx" ON "service_contracts" (tenant_id);
--> statement-breakpoint
ALTER TABLE "sites" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "sites" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS sites_tenant_isolation ON "sites";
--> statement-breakpoint
CREATE POLICY sites_tenant_isolation ON "sites"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sites_tenant_rls_idx" ON "sites" (tenant_id);
--> statement-breakpoint
ALTER TABLE "staff_schedules" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "staff_schedules" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS staff_schedules_tenant_isolation ON "staff_schedules";
--> statement-breakpoint
CREATE POLICY staff_schedules_tenant_isolation ON "staff_schedules"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "staff_schedules_tenant_rls_idx" ON "staff_schedules" (tenant_id);
--> statement-breakpoint
ALTER TABLE "stock_count_lines" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "stock_count_lines" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS stock_count_lines_tenant_isolation ON "stock_count_lines";
--> statement-breakpoint
CREATE POLICY stock_count_lines_tenant_isolation ON "stock_count_lines"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_count_lines_tenant_rls_idx" ON "stock_count_lines" (tenant_id);
--> statement-breakpoint
ALTER TABLE "stock_counts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "stock_counts" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS stock_counts_tenant_isolation ON "stock_counts";
--> statement-breakpoint
CREATE POLICY stock_counts_tenant_isolation ON "stock_counts"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_counts_tenant_rls_idx" ON "stock_counts" (tenant_id);
--> statement-breakpoint
ALTER TABLE "stock_levels" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "stock_levels" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS stock_levels_tenant_isolation ON "stock_levels";
--> statement-breakpoint
CREATE POLICY stock_levels_tenant_isolation ON "stock_levels"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_levels_tenant_rls_idx" ON "stock_levels" (tenant_id);
--> statement-breakpoint
ALTER TABLE "stock_moves" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "stock_moves" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS stock_moves_tenant_isolation ON "stock_moves";
--> statement-breakpoint
CREATE POLICY stock_moves_tenant_isolation ON "stock_moves"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_moves_tenant_rls_idx" ON "stock_moves" (tenant_id);
--> statement-breakpoint
ALTER TABLE "supplier_profiles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "supplier_profiles" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS supplier_profiles_tenant_isolation ON "supplier_profiles";
--> statement-breakpoint
CREATE POLICY supplier_profiles_tenant_isolation ON "supplier_profiles"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "supplier_profiles_tenant_rls_idx" ON "supplier_profiles" (tenant_id);
--> statement-breakpoint
ALTER TABLE "tax_codes" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "tax_codes" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS tax_codes_tenant_isolation ON "tax_codes";
--> statement-breakpoint
CREATE POLICY tax_codes_tenant_isolation ON "tax_codes"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tax_codes_tenant_rls_idx" ON "tax_codes" (tenant_id);
--> statement-breakpoint
ALTER TABLE "units" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "units" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS units_tenant_isolation ON "units";
--> statement-breakpoint
CREATE POLICY units_tenant_isolation ON "units"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "units_tenant_rls_idx" ON "units" (tenant_id);
--> statement-breakpoint
ALTER TABLE "user_invites" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "user_invites" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS user_invites_tenant_isolation ON "user_invites";
--> statement-breakpoint
CREATE POLICY user_invites_tenant_isolation ON "user_invites"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_invites_tenant_rls_idx" ON "user_invites" (tenant_id);
--> statement-breakpoint
ALTER TABLE "vat_returns" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "vat_returns" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS vat_returns_tenant_isolation ON "vat_returns";
--> statement-breakpoint
CREATE POLICY vat_returns_tenant_isolation ON "vat_returns"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vat_returns_tenant_rls_idx" ON "vat_returns" (tenant_id);
--> statement-breakpoint
ALTER TABLE "warehouses" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "warehouses" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS warehouses_tenant_isolation ON "warehouses";
--> statement-breakpoint
CREATE POLICY warehouses_tenant_isolation ON "warehouses"
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "warehouses_tenant_rls_idx" ON "warehouses" (tenant_id);
--> statement-breakpoint
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "tenants" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS tenants_self_isolation ON "tenants";
--> statement-breakpoint
CREATE POLICY tenants_self_isolation ON "tenants"
      USING (id = current_setting('app.tenant_id', true)::uuid)
      WITH CHECK (id = current_setting('app.tenant_id', true)::uuid);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION assert_journal_balanced() RETURNS trigger AS $$
    DECLARE
      d numeric(18,4);
      c numeric(18,4);
    BEGIN
      SELECT COALESCE(SUM(base_debit),0), COALESCE(SUM(base_credit),0)
        INTO d, c
        FROM journal_lines
       WHERE journal_id = COALESCE(NEW.journal_id, OLD.journal_id);
      IF d <> c THEN
        RAISE EXCEPTION 'Journal % is unbalanced: debit %, credit %',
          COALESCE(NEW.journal_id, OLD.journal_id), d, c;
      END IF;
      RETURN NULL;
    END $$ LANGUAGE plpgsql;
--> statement-breakpoint
DROP TRIGGER IF EXISTS journal_balance_check ON journal_lines;
--> statement-breakpoint
CREATE CONSTRAINT TRIGGER journal_balance_check
      AFTER INSERT OR UPDATE OR DELETE ON journal_lines
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION assert_journal_balanced();
--> statement-breakpoint
ALTER TABLE journal_lines DROP CONSTRAINT IF EXISTS journal_lines_single_side;
--> statement-breakpoint
ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_single_side
      CHECK ((debit = 0 AND credit > 0) OR (credit = 0 AND debit > 0) OR (debit = 0 AND credit = 0));
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS leases_one_active_per_unit
      ON leases (unit_id) WHERE status = 'active';
--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS btree_gist;
--> statement-breakpoint
ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_no_resource_overlap;
--> statement-breakpoint
ALTER TABLE appointments ADD CONSTRAINT appointments_no_resource_overlap
      EXCLUDE USING gist (
        resource_id WITH =,
        tstzrange(starts_at, ends_at) WITH &&
      ) WHERE (resource_id IS NOT NULL AND status NOT IN ('cancelled','no_show'));
--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS parties_search_trgm
      ON parties USING gin ((display_name || ' ' || COALESCE(primary_phone,'')) gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS items_search_trgm
      ON items USING gin (name gin_trgm_ops);
